SSystemsBackendBundle_admin_s_systems_backend_bundle_AdminClientProfile:
    resource: "@SSystemsBackendBundle/Controller/AdminClientProfile/"
    type:     admingenerator
    prefix:   /admin/clients

SSystemsBackendBundle_admin_s_systems_backend_bundle_AdminImages:
    resource: "@SSystemsBackendBundle/Controller/AdminImages/"
    type:     admingenerator
    prefix:   /admin/images

SSystemsBackendBundle_admin_s_systems_backend_bundle_AdminCollaboratorProfile:
    resource: "@SSystemsBackendBundle/Controller/AdminCollaboratorProfile/"
    type:     admingenerator
    prefix:   /admin/collaborators

SSystemsBackendBundle_admin_s_systems_backend_bundle_AdminPurchase:
    resource: "@SSystemsBackendBundle/Controller/AdminPurchase/"
    type:     admingenerator
    prefix:   /admin/purchases

estocBundle:
    resource: "@EstocBundle/Resources/config/routing.yml"
    prefix:   /

_imagine:
    resource: .
    type:     imagine

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /admin

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile