<?php

namespace SSystems\EstocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientProfileRepository extends EntityRepository
{
    public function findClients(){
        $query = $this->createQueryBuilder('clpf')
            ->select('clpf','usr')
            ->join('clpf.user','usr')
        ;

        return $query;
    }
}
