<?php

namespace SSystems\EstocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollaboratorProfileRepository extends EntityRepository
{
    public function findUnpaidPurchasesFromCollaborator($id){
        $query = $this->createQueryBuilder('cp')
            ->select('cp','u','im','ip','ipis','p','ipu','clp')
            ->join('cp.user','u')
            ->join('u.images','im')
            ->join('im.purchaseDetails','ip')
            ->join('ip.imageSize','ipis')
            ->join('ip.purchase','p')
            ->join('p.user','ipu')
            ->join('ipu.clientProfile','clp')
            ->where('cp.id = :id')
            ->andWhere('p.charge = true')
            ->andWhere('ip.paid = false')
            ->setParameter('id',$id);

        return $query->getQuery()->getSingleResult();
    }

    public function findCollaborators(){
        $query = $this->createQueryBuilder('copr')
            ->select('copr','usr','img','pude','pu')
            ->join('copr.user','usr')
            ->leftJoin('usr.images','img')
            ->leftJoin('img.purchaseDetails','pude')
            ->leftJoin('pude.purchase','pu')
        ;

        return $query;
    }
}
