<?php

namespace SSystems\EstocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    public function findImagesByIds($ids,$cant = NULL){
        if(empty($ids)){
            return false;
        }
        $query = $this->createQueryBuilder('i')
            ->select('i')
            ->andWhere("i.id IN (:ids)")
            ->andWhere("i.active = true")
            ->andWhere("i.exclusive = false")
            ->setParameter('ids',$ids)
        ;
        if($cant != NULL){
            $query->setMaxResults($cant);
        }
        return $query->getQuery()->getResult();
    }

    public function findImagesByCant($cant){
        $query = $this->createQueryBuilder('i')
            ->select('i')
            ->andWhere("i.active = true")
            ->andWhere("i.exclusive = false")
            ->setMaxResults($cant)
            ;

        return $query->getQuery()->getResult();
    }

    public function findAll(){
        return $this->findBy(
            array(
                'active' => true,
                'exclusive' => false,
            )
        );
    }

    public function findByUser($useId){
        $query = $this->createQueryBuilder('i')
            ->select('i','usr','cnt')
            ->join('i.user','usr')
            ->where('usr.id = :id')
            ->where('i.contract','cnt')
            ->setParameter('id',$useId)
        ;
        return $query->getQuery()->getResult();
    }
}
