<?php

namespace SSystems\EstocBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findUserWithImage($id){
        $query = $this->createQueryBuilder('usr')
            ->select('usr','img','clpf','cnt')
            ->leftJoin('usr.images','img')
            ->leftJoin('img.contract','cnt')
            ->join('usr.collaboratorProfile','clpf')
            ->where('usr.id = :id')
            ->setParameter('id',$id)
        ;

        return $query->getQuery()->getSingleResult();
    }
}
